// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: main.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Summary              string               `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Complexity           string               `protobuf:"bytes,3,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Container            string               `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	GetKeysFunction      string               `protobuf:"bytes,5,opt,name=get_keys_function,json=getKeysFunction,proto3" json:"get_keys_function,omitempty"`
	Group                string               `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Since                string               `protobuf:"bytes,7,opt,name=since,proto3" json:"since,omitempty"`
	Arity                int32                `protobuf:"varint,8,opt,name=arity,proto3" json:"arity,omitempty"`
	Function             string               `protobuf:"bytes,9,opt,name=function,proto3" json:"function,omitempty"`
	CommandFlags         []string             `protobuf:"bytes,10,rep,name=command_flags,json=commandFlags,proto3" json:"command_flags,omitempty"`
	AclCategories        []string             `protobuf:"bytes,11,rep,name=acl_categories,json=aclCategories,proto3" json:"acl_categories,omitempty"`
	KeySpecs             []*Command_KeySpec   `protobuf:"bytes,12,rep,name=key_specs,json=keySpecs,proto3" json:"key_specs,omitempty"`
	ReplySchema          *Command_ReplySchema `protobuf:"bytes,13,opt,name=reply_schema,json=replySchema,proto3" json:"reply_schema,omitempty"`
	Arguments            []*Command_Argument  `protobuf:"bytes,14,rep,name=arguments,proto3" json:"arguments,omitempty"`
	History              []string             `protobuf:"bytes,15,rep,name=history,proto3" json:"history,omitempty"`
	AdditionalProperties bool                 `protobuf:"varint,16,opt,name=additionalProperties,proto3" json:"additionalProperties,omitempty"`
	Properties           *Command_Properties  `protobuf:"bytes,17,opt,name=properties,proto3" json:"properties,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Command) GetComplexity() string {
	if x != nil {
		return x.Complexity
	}
	return ""
}

func (x *Command) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *Command) GetGetKeysFunction() string {
	if x != nil {
		return x.GetKeysFunction
	}
	return ""
}

func (x *Command) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Command) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *Command) GetArity() int32 {
	if x != nil {
		return x.Arity
	}
	return 0
}

func (x *Command) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *Command) GetCommandFlags() []string {
	if x != nil {
		return x.CommandFlags
	}
	return nil
}

func (x *Command) GetAclCategories() []string {
	if x != nil {
		return x.AclCategories
	}
	return nil
}

func (x *Command) GetKeySpecs() []*Command_KeySpec {
	if x != nil {
		return x.KeySpecs
	}
	return nil
}

func (x *Command) GetReplySchema() *Command_ReplySchema {
	if x != nil {
		return x.ReplySchema
	}
	return nil
}

func (x *Command) GetArguments() []*Command_Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Command) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Command) GetAdditionalProperties() bool {
	if x != nil {
		return x.AdditionalProperties
	}
	return false
}

func (x *Command) GetProperties() *Command_Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Command_KeySpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags       []string                     `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	BeginSearch *Command_KeySpec_BeginSearch `protobuf:"bytes,2,opt,name=begin_search,json=beginSearch,proto3" json:"begin_search,omitempty"`
	FindKeys    *Command_KeySpec_FindKeys    `protobuf:"bytes,3,opt,name=find_keys,json=findKeys,proto3" json:"find_keys,omitempty"`
}

func (x *Command_KeySpec) Reset() {
	*x = Command_KeySpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_KeySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_KeySpec) ProtoMessage() {}

func (x *Command_KeySpec) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_KeySpec.ProtoReflect.Descriptor instead.
func (*Command_KeySpec) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Command_KeySpec) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *Command_KeySpec) GetBeginSearch() *Command_KeySpec_BeginSearch {
	if x != nil {
		return x.BeginSearch
	}
	return nil
}

func (x *Command_KeySpec) GetFindKeys() *Command_KeySpec_FindKeys {
	if x != nil {
		return x.FindKeys
	}
	return nil
}

type Command_ReplySchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnyOf []*Command_ReplySchema_Item `protobuf:"bytes,1,rep,name=AnyOf,proto3" json:"AnyOf,omitempty"`
	OneOf []*Command_ReplySchema_Item `protobuf:"bytes,2,rep,name=OneOf,proto3" json:"OneOf,omitempty"`
}

func (x *Command_ReplySchema) Reset() {
	*x = Command_ReplySchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_ReplySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_ReplySchema) ProtoMessage() {}

func (x *Command_ReplySchema) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_ReplySchema.ProtoReflect.Descriptor instead.
func (*Command_ReplySchema) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Command_ReplySchema) GetAnyOf() []*Command_ReplySchema_Item {
	if x != nil {
		return x.AnyOf
	}
	return nil
}

func (x *Command_ReplySchema) GetOneOf() []*Command_ReplySchema_Item {
	if x != nil {
		return x.OneOf
	}
	return nil
}

type Command_Argument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type         string              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	KeySpecIndex int32               `protobuf:"varint,3,opt,name=key_spec_index,json=keySpecIndex,proto3" json:"key_spec_index,omitempty"`
	Token        string              `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Optional     bool                `protobuf:"varint,5,opt,name=optional,proto3" json:"optional,omitempty"`
	Arguments    []*Command_Argument `protobuf:"bytes,6,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *Command_Argument) Reset() {
	*x = Command_Argument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Argument) ProtoMessage() {}

func (x *Command_Argument) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Argument.ProtoReflect.Descriptor instead.
func (*Command_Argument) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Command_Argument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command_Argument) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command_Argument) GetKeySpecIndex() int32 {
	if x != nil {
		return x.KeySpecIndex
	}
	return 0
}

func (x *Command_Argument) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Command_Argument) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *Command_Argument) GetArguments() []*Command_Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type Command_Properties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Properties map[string]*Command_Properties_PropertyValue `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Command_Properties) Reset() {
	*x = Command_Properties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Properties) ProtoMessage() {}

func (x *Command_Properties) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Properties.ProtoReflect.Descriptor instead.
func (*Command_Properties) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Command_Properties) GetProperties() map[string]*Command_Properties_PropertyValue {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Command_KeySpec_BeginSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index *Command_KeySpec_BeginSearch_Index `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *Command_KeySpec_BeginSearch) Reset() {
	*x = Command_KeySpec_BeginSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_KeySpec_BeginSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_KeySpec_BeginSearch) ProtoMessage() {}

func (x *Command_KeySpec_BeginSearch) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_KeySpec_BeginSearch.ProtoReflect.Descriptor instead.
func (*Command_KeySpec_BeginSearch) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Command_KeySpec_BeginSearch) GetIndex() *Command_KeySpec_BeginSearch_Index {
	if x != nil {
		return x.Index
	}
	return nil
}

type Command_KeySpec_FindKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range *Command_KeySpec_FindKeys_Range `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
}

func (x *Command_KeySpec_FindKeys) Reset() {
	*x = Command_KeySpec_FindKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_KeySpec_FindKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_KeySpec_FindKeys) ProtoMessage() {}

func (x *Command_KeySpec_FindKeys) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_KeySpec_FindKeys.ProtoReflect.Descriptor instead.
func (*Command_KeySpec_FindKeys) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Command_KeySpec_FindKeys) GetRange() *Command_KeySpec_FindKeys_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type Command_KeySpec_BeginSearch_Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos int32 `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *Command_KeySpec_BeginSearch_Index) Reset() {
	*x = Command_KeySpec_BeginSearch_Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_KeySpec_BeginSearch_Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_KeySpec_BeginSearch_Index) ProtoMessage() {}

func (x *Command_KeySpec_BeginSearch_Index) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_KeySpec_BeginSearch_Index.ProtoReflect.Descriptor instead.
func (*Command_KeySpec_BeginSearch_Index) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Command_KeySpec_BeginSearch_Index) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

type Command_KeySpec_FindKeys_Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lastkey int32 `protobuf:"varint,1,opt,name=lastkey,proto3" json:"lastkey,omitempty"`
	Step    int32 `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Limit   int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *Command_KeySpec_FindKeys_Range) Reset() {
	*x = Command_KeySpec_FindKeys_Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_KeySpec_FindKeys_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_KeySpec_FindKeys_Range) ProtoMessage() {}

func (x *Command_KeySpec_FindKeys_Range) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_KeySpec_FindKeys_Range.ProtoReflect.Descriptor instead.
func (*Command_KeySpec_FindKeys_Range) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *Command_KeySpec_FindKeys_Range) GetLastkey() int32 {
	if x != nil {
		return x.Lastkey
	}
	return 0
}

func (x *Command_KeySpec_FindKeys_Range) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Command_KeySpec_FindKeys_Range) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Command_ReplySchema_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string                      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description string                      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	MaxItems    int32                       `protobuf:"varint,3,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	MinItems    int32                       `protobuf:"varint,4,opt,name=minItems,proto3" json:"minItems,omitempty"`
	Items       []*Command_ReplySchema_Item `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Command_ReplySchema_Item) Reset() {
	*x = Command_ReplySchema_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_ReplySchema_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_ReplySchema_Item) ProtoMessage() {}

func (x *Command_ReplySchema_Item) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_ReplySchema_Item.ProtoReflect.Descriptor instead.
func (*Command_ReplySchema_Item) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Command_ReplySchema_Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command_ReplySchema_Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Command_ReplySchema_Item) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *Command_ReplySchema_Item) GetMinItems() int32 {
	if x != nil {
		return x.MinItems
	}
	return 0
}

func (x *Command_ReplySchema_Item) GetItems() []*Command_ReplySchema_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Command_Properties_PropertyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Command_Properties_PropertyValue_StringValue
	//	*Command_Properties_PropertyValue_PropertiesValue
	Value isCommand_Properties_PropertyValue_Value `protobuf_oneof:"value"`
}

func (x *Command_Properties_PropertyValue) Reset() {
	*x = Command_Properties_PropertyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_Properties_PropertyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Properties_PropertyValue) ProtoMessage() {}

func (x *Command_Properties_PropertyValue) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Properties_PropertyValue.ProtoReflect.Descriptor instead.
func (*Command_Properties_PropertyValue) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (m *Command_Properties_PropertyValue) GetValue() isCommand_Properties_PropertyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Command_Properties_PropertyValue) GetStringValue() string {
	if x, ok := x.GetValue().(*Command_Properties_PropertyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Command_Properties_PropertyValue) GetPropertiesValue() *Command_Properties {
	if x, ok := x.GetValue().(*Command_Properties_PropertyValue_PropertiesValue); ok {
		return x.PropertiesValue
	}
	return nil
}

type isCommand_Properties_PropertyValue_Value interface {
	isCommand_Properties_PropertyValue_Value()
}

type Command_Properties_PropertyValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=stringValue,proto3,oneof"`
}

type Command_Properties_PropertyValue_PropertiesValue struct {
	PropertiesValue *Command_Properties `protobuf:"bytes,2,opt,name=propertiesValue,proto3,oneof"`
}

func (*Command_Properties_PropertyValue_StringValue) isCommand_Properties_PropertyValue_Value() {}

func (*Command_Properties_PropertyValue_PropertiesValue) isCommand_Properties_PropertyValue_Value() {}

var File_main_proto protoreflect.FileDescriptor

var file_main_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0xfd, 0x0e, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x69, 0x74, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x2a, 0x0a,
	0x11, 0x67, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x61, 0x63, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x73,
	0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x08, 0x6b, 0x65, 0x79, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x3f, 0x0a, 0x0c, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x0b,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x37, 0x0a, 0x09, 0x61,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x0f, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x32,
	0x0a, 0x14, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x61, 0x64,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a,
	0xad, 0x03, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67,
	0x73, 0x12, 0x47, 0x0a, 0x0c, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x70, 0x65,
	0x63, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x0b, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x3e, 0x0a, 0x09, 0x66, 0x69,
	0x6e, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e,
	0x4b, 0x65, 0x79, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x08, 0x66, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x1a, 0x6a, 0x0a, 0x0b, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x40, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x70,
	0x65, 0x63, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x19, 0x0a, 0x05, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x1a, 0x96, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x4b,
	0x65, 0x79, 0x73, 0x12, 0x3d, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x4b, 0x65, 0x79, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x1a, 0x4b, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x61, 0x73, 0x74, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x61,
	0x73, 0x74, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x1a,
	0xaf, 0x02, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12,
	0x37, 0x0a, 0x05, 0x41, 0x6e, 0x79, 0x4f, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x41, 0x6e, 0x79, 0x4f, 0x66, 0x12, 0x37, 0x0a, 0x05, 0x4f, 0x6e, 0x65, 0x4f,
	0x66, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x4f, 0x6e, 0x65, 0x4f,
	0x66, 0x1a, 0xad, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x69, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6d, 0x69, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x1a, 0xc3, 0x01, 0x0a, 0x08, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x70,
	0x65, 0x63, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x6b, 0x65, 0x79, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x37,
	0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x61, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0xcb, 0x02, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x1a, 0x85, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x68, 0x0a, 0x0f, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x3f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65, 0x79, 0x37, 0x30, 0x30, 0x37, 0x2f,
	0x72, 0x65, 0x64, 0x69, 0x73, 0x73, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData = file_main_proto_rawDesc
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_main_proto_rawDescData)
	})
	return file_main_proto_rawDescData
}

var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_main_proto_goTypes = []interface{}{
	(*Command)(nil),                           // 0: command.Command
	(*Command_KeySpec)(nil),                   // 1: command.Command.KeySpec
	(*Command_ReplySchema)(nil),               // 2: command.Command.ReplySchema
	(*Command_Argument)(nil),                  // 3: command.Command.Argument
	(*Command_Properties)(nil),                // 4: command.Command.Properties
	(*Command_KeySpec_BeginSearch)(nil),       // 5: command.Command.KeySpec.BeginSearch
	(*Command_KeySpec_FindKeys)(nil),          // 6: command.Command.KeySpec.FindKeys
	(*Command_KeySpec_BeginSearch_Index)(nil), // 7: command.Command.KeySpec.BeginSearch.Index
	(*Command_KeySpec_FindKeys_Range)(nil),    // 8: command.Command.KeySpec.FindKeys.Range
	(*Command_ReplySchema_Item)(nil),          // 9: command.Command.ReplySchema.Item
	(*Command_Properties_PropertyValue)(nil),  // 10: command.Command.Properties.PropertyValue
	nil,                                       // 11: command.Command.Properties.PropertiesEntry
}
var file_main_proto_depIdxs = []int32{
	1,  // 0: command.Command.key_specs:type_name -> command.Command.KeySpec
	2,  // 1: command.Command.reply_schema:type_name -> command.Command.ReplySchema
	3,  // 2: command.Command.arguments:type_name -> command.Command.Argument
	4,  // 3: command.Command.properties:type_name -> command.Command.Properties
	5,  // 4: command.Command.KeySpec.begin_search:type_name -> command.Command.KeySpec.BeginSearch
	6,  // 5: command.Command.KeySpec.find_keys:type_name -> command.Command.KeySpec.FindKeys
	9,  // 6: command.Command.ReplySchema.AnyOf:type_name -> command.Command.ReplySchema.Item
	9,  // 7: command.Command.ReplySchema.OneOf:type_name -> command.Command.ReplySchema.Item
	3,  // 8: command.Command.Argument.arguments:type_name -> command.Command.Argument
	11, // 9: command.Command.Properties.properties:type_name -> command.Command.Properties.PropertiesEntry
	7,  // 10: command.Command.KeySpec.BeginSearch.index:type_name -> command.Command.KeySpec.BeginSearch.Index
	8,  // 11: command.Command.KeySpec.FindKeys.range:type_name -> command.Command.KeySpec.FindKeys.Range
	9,  // 12: command.Command.ReplySchema.Item.items:type_name -> command.Command.ReplySchema.Item
	4,  // 13: command.Command.Properties.PropertyValue.propertiesValue:type_name -> command.Command.Properties
	10, // 14: command.Command.Properties.PropertiesEntry.value:type_name -> command.Command.Properties.PropertyValue
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_KeySpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_ReplySchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_Argument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_Properties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_KeySpec_BeginSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_KeySpec_FindKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_KeySpec_BeginSearch_Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_KeySpec_FindKeys_Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_ReplySchema_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_Properties_PropertyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_main_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*Command_Properties_PropertyValue_StringValue)(nil),
		(*Command_Properties_PropertyValue_PropertiesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_rawDesc = nil
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
